### ISSUE TITLE
filenames with dots don't work properly

### ISSUE THREAD

**Issue by rbuysse** [rbuysse/grombley#21]
in FF 117 on osx it brings up a file save dialog

**Comment by shmup** [comment]
can you tell me how to replicate this? i'm testing on FF 112 in linux

i've tried pasting in this url with success:

`https://dev.host/~shmup/tmp/t r i.png`

i also browsed for it

**Comment by rbuysse** [comment]
Oops my bad, it's not spaces, it's dots in the filename.

Trying with "Screenshot 2023-09-14 at 12.42.04 PM.png"

**Comment by rbuysse** [comment]
good job
