### ISSUE TITLE
Image URL uploading fails because of CORS

### ISSUE THREAD

**Issue by rbuysse** [rbuysse/grombley#4]
@shmup plz fix

`
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://i.dailymail.co.uk/i/pix/2017/01/10/14/3C0564BA00000578-4105544-image-a-86_1484057171207.jpg. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
`

**Comment by shmup** [comment]
PR up soon

![image](https://github.com/rbuysse/grombley/assets/118710/078405a0-4e26-44b4-ba5d-df2ea478efd0)
